import React, { useRef, useImperativeHandle, forwardRef } from "react";
import html2canvas from "html2canvas";
import { getProxyImageUrl } from "../utils/apiConfig";

const DeckImageGenerator = forwardRef((props, ref) => {
  const containerRef = useRef(null);

  // 外部から呼び出せる関数を定義
  useImperativeHandle(ref, () => ({
    generateImage: async (deckName, cards) => {
      if (!containerRef.current) return;
      
      // 画像生成処理
      try {
        // 一瞬だけ表示してレンダリングさせる必要があるため、親側で制御するか、
        // ここでstyleを操作して可視化→画像化→非表示にする手もあるが、
        // html2canvasは可視要素でないとうまく撮れないことが多い。
        // 親側で「生成中はオーバーレイ表示」などにするのが一般的。
        
        const canvas = await html2canvas(containerRef.current, {
          useCORS: true, // 別ドメインの画像(proxy)を扱うために必須
          scale: 2, // 高画質化
          backgroundColor: "#000000"
        });
        
        // 画像ダウンロード
        const link = document.createElement("a");
        link.download = `${deckName || "deck"}.png`;
        link.href = canvas.toDataURL("image/png");
        link.click();
      } catch (err) {
        console.error("Image generation failed:", err);
        alert("画像の生成に失敗しました。\n・通信環境を確認してください\n・画像の読み込みが完了していない可能性があります");
      }
    }
  }));

  const { deckName, cards } = props;

  // 40枚に満たない場合は空のスロットで埋める（一応）
  const displayCards = [...(cards || [])];
  while (displayCards.length < 40) {
    displayCards.push(null);
  }

  return (
    <div style={{ position: "fixed", top: "-9999px", left: "-9999px" }}>
    {/* 実際の生成用コンテナ (画面外には配置するが、display:noneだと撮れないので座標飛ばし) */}
      <div 
        ref={containerRef}
        style={{ 
          width: "1200px", // 高解像度向けに大きめに
          background: "#121212", 
          padding: "20px",
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          fontFamily: "sans-serif",
          color: "white"
        }}
      >
        <div style={{ fontSize: "2rem", fontWeight: "bold", marginBottom: "20px", borderBottom: "2px solid #007bff", paddingBottom: "10px", width: "100%", textAlign: "center" }}>
          {deckName || "No Name Deck"}
        </div>
        
        <div style={{ 
          display: "grid", 
          gridTemplateColumns: "repeat(5, 1fr)", // 横5列
          gap: "10px",
          width: "100%"
        }}>
          {displayCards.map((url, i) => (
            <div key={i} style={{ aspectRatio: "63/88", position: "relative" }}>
              {url ? (
                <img 
                  src={getProxyImageUrl(url)} 
                  alt="" 
                  crossOrigin="anonymous" // これが重要
                  style={{ width: "100%", height: "100%", objectFit: "cover", borderRadius: "4px" }} 
                />
              ) : (
                <div style={{ width: "100%", height: "100%", background: "#222", borderRadius: "4px", border: "1px dashed #444" }}></div>
              )}
            </div>
          ))}
        </div>
        
        <div style={{ marginTop: "20px", fontSize: "1rem", color: "#888", alignSelf: "flex-end" }}>
          Generated by Duema Online
        </div>
      </div>
    </div>
  );
});

export default DeckImageGenerator;
